function process_phase_circ_plot(filename_h, amp_range)
S = load(['Trials_' filename_h '.mat']);
f_num = length(S.Trials);
for i = 1:f_num
    clearvars c_phase
    F = figure;
    c_phase = S.Trials(i).Phase(S.Trials(i).Amps>amp_range(1)&S.Trials(i).Amps<amp_range(end));
    A = circ_plot(c_phase,'pretty');
    set(A,'Visible','off')
    set(A.Children(end),'LineWidth',2);
    set(A.Children(end-4),'LineWidth',4);
    text(-0.8,1.3, [S.Trials(i).Filename ' Freq: ' num2str(S.Trials(i).S_freq) ' Amp: ' num2str(S.Trials(i).S_amp)],...
    'interpreter','none',...
    'FontWeight','bold',...
    'FontSize',12)
    text(-1.2,1.2,['R: ' num2str(circ_r(c_phase))],...
    'FontWeight','bold',...
    'FontSize',12)
    text(-1.2,1.1,['Mean direction: ' num2str(rad2deg(circ_mean(c_phase))) ' degree'],...
    'FontWeight','bold',...
    'FontSize',12)
    text(-1.2,1,['STD: ' num2str(rad2deg(circ_std(c_phase))) ' degree'],...
    'FontWeight','bold',...
    'FontSize',12)
    print([S.Trials(i).Filename '_' num2str(round(S.Trials(i).S_freq,1)) 'Hz_' num2str(round(S.Trials(i).S_amp,2)) 'g(' num2str(amp_range(1)) 'to' num2str(amp_range(end)) 'pA).pdf'],'-fillpage','-dpdf')
end
close all
end
